version: '3'

services:
  db_new:
    image: postgres:16.3
    restart: no
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: CSM-LOCAL-DB
    volumes:
      - ./postgres_new:/var/lib/postgresql/data